# Site
name: Charles Stephen Thompson
description: The HandyHomo
meta_description: My Personal Site
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl: /
email: 'hello@c@handyhomo.com'
google_analytics: UA-103662447-9
disqus:
sharethis:

# Authors
authors:
  Charles:
    name: Charles
    display_name: Charles Stephen Thompson, The HandyHomo
    image: /assets/images/john.jpg
    email: hello@handyhomo.com
    web: http://cst.wtf
    twitter:
    description: Hi, I'm the HandyHomo.

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: handyhomo
  card: summary

facebook:
  app_id:
  publisher: charlestephen
  admins:

social:
name: John Doe
links:
    - https://twitter.com/handyhomo
    - https://www.facebook.com/charlestephen
    - https://www.linkedin.com/mrcharlestephen
    - https://github.com/charlestephen
